
language: node_js
notifications:
  slack: ub-cdp-2018:tlGf8J1sCs4WFLOf60GVfKJU
services:
- docker
node_js:
- '8'
addons:
  sonarcloud:
    organization: "acherifi-github" # the key of the org you chose at step #3
    token:
      secure: "$SONAR_TOKEN" # encrypted value of your token

install:
  - docker-compose -f docker-compose-dev.yml up --build -d
  - npm install

script:
  - npm test 
  - npm run teste2e

after_script:
  - sonar-scanner

before_deploy:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASS"
- git config --local user.name "Ali"
- git config --local user.email "cherifiali@outlook.fr"
- docker build . -t "annihilerb/cdp:$TRAVIS_TAG"
- docker tag "annihilerb/cdp:$TRAVIS_TAG" "annihilerb/cdp:latest"
- docker push annihilerb/cdp:$TRAVIS_TAG
- docker push annihilerb/cdp:latest

deploy:
  provider: script
  script: bash ./scripts/deploy.sh
  on:
    tags: true
    branches:
      only:
        - /v\d+\.\d+/
