language: node_js
services:
- docker
branches:
  only:
    - release
node_js:
- '8'
install:
  - npm install
before_deploy:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASS"
- git config --local user.name "Ali"
- git config --local user.email "cherifiali@outlook.fr"
- docker build . -t "annihilerb/cdp:$TRAVIS_TAG"
- docker tag "annihilerb/cdp:$TRAVIS_TAG" "annihilerb/cdp:latest"
- docker push annihilerb/cdp:$TRAVIS_TAG
- docker push annihilerb/cdp:latest
deploy:
  provider: releases
  api_key:
    secure: RGNh2MlQ5M74HsVHY/tqW+y3jdydiSHCtJIOAMbftN0ghCZsekYcSRsEYmgZmadaHnXunfTXGS/nT3l4vFM1Pp9nxX6tTeHkqOuF9xlznksH5oiN7Gc+HyuCxV+SRYTJU+DOV7Rqbt9yfdBlTUa290XiXZm+L2VEHEBc6Zduj2R3ez3VQTZV3kzyE74LxPeebUVhN20PPNV9n7T9Y/det5B11jzIJ4tMANj1untn/AaldiIaTNlhGAqCr/AgQAXLTmQ/Kp/Z+dQv6zk6qKAPB089+2PaDWKednwojbAVABWG0q6gJSxMAY3jSDtR4iqiK3/5ksQyHDOJ7HNcGRvaK53ZIxEyCqSpluJOpe2g4bUo8G/tBUBY2IgRYnxb/qrQD3l8uOB+ojiICcNO+qzOYG1l5xlNdNdwFUftLgxYAzmuoJkKEOjtxinbIcQFC6bjCyTF0yOT6pYyHOI8g8yZ8uoyNy+QQhrQqP8dho33tejS+EcrhI5vWnmUm3PrcFumujeZ3PhyTN2n0MlZgbXXkuI/RkHoUuibGIvhznl1RheunoBT22V9ZC8bwIVKsucPMvdiHnoEJmYEIAuZTsmLQVZoVCq/FmzOc4N/uNKvDewnQc+bXajXzsy6Rhj5uHenKqbKlwSyvRbB15jFk2HvJcBjSvbjx5tACvNwticyNc4=
  file: docker-compose.yml
  on:
    repo: AnnihilerB/cdp-2018
    branch: release
    tags: true
