# Use root/example as user/password credentials
version: '3.1'

services:
  web:
    container_name: webappcdp
    restart : always
    build: .
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src

  db:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: cdp
    volumes:
      - ./resources/cdp.sql:/docker-entrypoint-initdb.d/cdp.sql

  adminer:
    container_name: adminersql
    image: adminer
    restart: always
    ports:
      - 8081:8080