# Use root/example as user/password credentials
version: '3.1'

services:
  web:
    container_name: webappcdp
    restart : always
    build: .
    depends_on:
      - db
    ports:
      - 3000:3000 

  db:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: cdp
    volumes:
      - ./resources/cdp.sql:/docker-entrypoint-initdb.d/cdp.sql

  adminer:
    container_name: adminersql
    image: adminer
    restart: always
    ports:
      - 8081:8080

  chrome-selenium:
    image: selenium/node-chrome:3.14.0-gallium
    volumes:
      - ./shm:/dev/smh
    depends_on:
      - hub
    links:
      - web
    environment:
      HUB_HOST: hub

  firefox:
    image: selenium/node-firefox:3.14.0-gallium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    image: selenium/hub:3.14.0-gallium
    links:
      - web
    ports:
      - "4444:4444"
    environment:
            - GRID_TIMEOUT=10000
            - GRID_BROWSER_TIMEOUT=10000
            - SE_OPTS=-browserTimeout 10 -timeout 10